export enum PostgresConfigKeys {
    POSTGRES_HOST = 'POSTGRES_HOST',
    POSTGRES_PORT = 'POSTGRES_PORT',
    POSTGRES_USERNAME = 'POSTGRES_USERNAME',
    POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
    POSTGRES_DATABASE = 'POSTGRES_DATABASE',
    POSTGRES_SCHEMA = 'POSTGRES_SCHEMA',
    TYPE = 'postgres'
}